/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_probeCredential_parameter_0$schema = z.object({
  'token': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_probeCredential_result$schema = z.object({
  'login': z.string().readonly(),
  'rateLimitRemaining': z.number().readonly(),
})
const _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_search_parameter_0$schema = z.object({
  'pushedFrom': z.string().readonly(),
  'pushedTo': z.string().readonly(),
  'page': z.number().readonly(),
  'perPage': z.number().readonly(),
})
const _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_search_result$schema = z.object({
  'total': z.number().readonly(),
  'incomplete': z.boolean().readonly(),
  'items': z.array(z.object({
  'id': z.number().readonly(),
  'fullName': z.string().readonly(),
  'name': z.string().readonly(),
  'owner': z.string().readonly(),
  'repositoryUrl': z.string().readonly(),
  'description': z.string().readonly(),
  'topics': z.array(z.string()).readonly(),
  'language': z.string().readonly().optional(),
  'stars': z.number().readonly(),
  'pushedAt': z.string().readonly(),
  'archived': z.boolean().readonly(),
})).readonly(),
  'rateLimitRemaining': z.number().readonly(),
  'rateLimitResetAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@lovstudio/dsh-plugin-marketplace',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/probeCredential',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'probeCredential',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/types#GitHubMarketCredentialProbeRequest',
            schema: _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_probeCredential_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/types#GitHubMarketCredentialProbeResult',
        schema: _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_probeCredential_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-market-github/src/index.ts","line":92,"column":9},
    },
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/search',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'search',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/types#GitHubMarketSearchRequest',
            schema: _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_search_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/types#GitHubMarketSearchPage',
        schema: _deepseek_ai_dsh_host_plugin_market_github_pluginMarketGithub_search_result$schema,
      },
      sourceLocation: {"file":"packages/host/plugin-market-github/src/index.ts","line":120,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
