/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_listStarred_result$schema = z.object({
  'fullNames': z.array(z.string()).readonly(),
  'truncated': z.boolean().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_probeCredential_parameter_0$schema = z.object({
  'token': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_probeCredential_result$schema = z.object({
  'login': z.string().readonly(),
  'rateLimitRemaining': z.number().readonly(),
  'scopes': z.array(z.string()).readonly(),
  'canStar': z.boolean().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_resolvePackage_parameter_0$schema = z.object({
  'fullName': z.string().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_resolvePackage_result$schema = z.object({
  'pkgName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'pkgVersion': z.union([z.undefined(), z.string()]).readonly().optional(),
  'npmPublished': z.boolean().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_search_parameter_0$schema = z.object({
  'pushedFrom': z.string().readonly(),
  'pushedTo': z.string().readonly(),
  'page': z.number().readonly(),
  'perPage': z.number().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_search_result$schema = z.object({
  'total': z.number().readonly(),
  'incomplete': z.boolean().readonly(),
  'items': z.array(z.object({
  'id': z.number().readonly(),
  'fullName': z.string().readonly(),
  'name': z.string().readonly(),
  'owner': z.string().readonly(),
  'repositoryUrl': z.string().readonly(),
  'description': z.string().readonly(),
  'topics': z.array(z.string()).readonly(),
  'language': z.union([z.undefined(), z.string()]).readonly().optional(),
  'stars': z.number().readonly(),
  'pushedAt': z.string().readonly(),
  'archived': z.boolean().readonly(),
})).readonly(),
  'rateLimitRemaining': z.number().readonly(),
  'rateLimitResetAt': z.number().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_setStar_parameter_0$schema = z.object({
  'fullName': z.string().readonly(),
  'starred': z.boolean().readonly(),
})
const _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_setStar_result$schema = z.object({
  'fullName': z.string(),
  'starred': z.boolean(),
})

export const TYPERT = {
  package: '@lovstudio/dsh-plugin-marketplace',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/listStarred',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'listStarred',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketStarredResult',
        schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_listStarred_result$schema,
      },
      sourceLocation: {"file":"packages/plugin-marketplace/src/host/index.ts","line":192,"column":9},
    },
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/probeCredential',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'probeCredential',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketCredentialProbeRequest',
            schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_probeCredential_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketCredentialProbeResult',
        schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_probeCredential_result$schema,
      },
      sourceLocation: {"file":"packages/plugin-marketplace/src/host/index.ts","line":121,"column":9},
    },
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/resolvePackage',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'resolvePackage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketPackageRequest',
            schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_resolvePackage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketPackageResult',
        schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_resolvePackage_result$schema,
      },
      sourceLocation: {"file":"packages/plugin-marketplace/src/host/index.ts","line":161,"column":9},
    },
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/search',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'search',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketSearchRequest',
            schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_search_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketSearchPage',
        schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_search_result$schema,
      },
      sourceLocation: {"file":"packages/plugin-marketplace/src/host/index.ts","line":239,"column":9},
    },
    {
      id: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/setStar',
      service: 'pluginMarketGithub',
      namespace: 'pluginMarketGithub',
      method: 'setStar',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lovstudio/dsh-plugin-marketplace/host#GitHubMarketStarRequest',
            schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_setStar_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-plugin-marketplace#pluginMarketGithub/setStar:result',
        schema: _lovstudio_dsh_plugin_marketplace_pluginMarketGithub_setStar_result$schema,
      },
      sourceLocation: {"file":"packages/plugin-marketplace/src/host/index.ts","line":216,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
