/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { GitHubMarketCredentialProbeRequest, GitHubMarketCredentialProbeResult, GitHubMarketSearchPage, GitHubMarketSearchRequest } from '@lovstudio/dsh-plugin-marketplace/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e4d61726b6574476974687562 {
    probeCredential: (request: GitHubMarketCredentialProbeRequest) => Promise<RemoteResult<GitHubMarketCredentialProbeResult>>
    search: (request: GitHubMarketSearchRequest) => Promise<RemoteResult<GitHubMarketSearchPage>>
  }
  interface TypertRemoteMap {
    'pluginMarketGithub/probeCredential': (request: GitHubMarketCredentialProbeRequest) => Promise<RemoteResult<GitHubMarketCredentialProbeResult>>
    'pluginMarketGithub/search': (request: GitHubMarketSearchRequest) => Promise<RemoteResult<GitHubMarketSearchPage>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginMarketGithub': TypertRemoteNamespace$706c7567696e4d61726b6574476974687562
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
